### ISSUE TITLE
Milestone One ToDos ?

### ISSUE THREAD

**Issue by ruiwanguk** [PRIDE-Cluster/cluster-design#2]
Since Noe is not going to be here on Thursday, I think we should start discussing the todos and who does what.  Let's use this issue to track our discussion. 

To me, the key facts for milestone one is:
- Release deadline 31st March 2015
- A landing interface for PRIDE Cluster project. [Mockup](https://github.com/PRIDE-Cluster/cluster-design/blob/master/mockups/home-page.png)
- An interface for downloading spectral libraries. [Mockup](https://github.com/PRIDE-Cluster/cluster-design/blob/master/mockups/spectral-library.png)
- An interface for search peptide sequences. [Mockup 1](https://github.com/PRIDE-Cluster/cluster-design/blob/master/mockups/peptide-search.png) [Mockup 2](https://github.com/PRIDE-Cluster/cluster-design/blob/master/mockups/peptide-search-chart.png)
- An interface for presenting cluster details. [Mockup](https://github.com/PRIDE-Cluster/cluster-design/blob/master/mockups/cluster.png)

**Comment by noedelta** [comment]
I would like to focus in:
-Solr issue related to search by peptide
-Interface for downloading the spectral libraries.
After that I will see what is still pending, but I prefer start with small steps.

What do you think?

**Comment by ypriverol** [comment]
I want to be focus in Web services and Solr engine realted things.

**Comment by ruiwanguk** [comment]
Subject to your approval, I would also suggest we assume different roles in the project:
- Web: Key person should be **Jose** since he has the most experience, Noe will be working closely with him as well.  
- Web Service: Since Web and Web Service are closely related, I would suggest that **Jose** and **Noe** can make decisions, **Yasset** can contribute as well. 
- Search: Key person should be **Noe** and **Jose** based on their past experience. Rui would like to contribute as well. 
- Database: Key person should be **Rui** since he has been working with the database before. **Yasset** will also contribute.

Would you agree ?

**Comment by ypriverol** [comment]
Rui I can help you also with the database, I want to refresh some concepts that would be importat for me.

**Comment by ruiwanguk** [comment]
Ok, I have updated my previous comments.

**Comment by ruiwanguk** [comment]
My intention is that the person(s) who are working on that component has the flexibility to create issues and organise todos.

**Comment by ypriverol** [comment]
We can create milestone and issues in each component and the person that is working in the components can work in the issues, etc. Them we can plug the components. The main person responsable for the component should follow each issue, etc.

**Comment by ruiwanguk** [comment]
Good point Yasset, I have already created the first milestone in all our components yesterday, I think we can just reuse it.

**Comment by jadianes** [comment]
Hi Guys,

I would like to be a key person in the **search** for two reasons. First of all I think that, although Noe started doing some development, most of the current code is mine, specially that related with the spectral search (I know is future work), the current data model and service, and with future scalability improvements. So here I would put Noe and myself as decisions makers. Also Noe has lots of pressure from the Archive and I don't think is practical to leave her with too much responsibility.

In the **web**, I can be responsible for a while. Let us say until the knowledge is transferred to the team, or until the 31st of March milestone. 

But in any case, I think all contributions are welcome from every side. We shouldn't stop anybody to open issues or assign them to her/himself after the approval of the person that owns most of the code in that particular part.

I agree with the rest of the proposal :)

**Comment by ruiwanguk** [comment]
@jadianes , I see your point. Actually, I was just talking about for milestone one. And of course, you will be the key person for the spectral search in the future. But this will be part of milestone two. 

Do you still want to change the key person?

**Comment by ruiwanguk** [comment]
To everyone, 

the idea of key person is to share responsibility and enable individuals to make decisions freely. Everyone are of course welcome to contribute to other part, but I thought that it is better to have some focus and an anchor point, and it is better to be upfront about this.

**Comment by jadianes** [comment]
Yes. Even for the first milestone I think it makes complete sense to keep me as one of the key persons. Again, my reasons are expertise and availability.

**Comment by ruiwanguk** [comment]
Great, I have changed the post.

**Comment by ruiwanguk** [comment]
As of next, shall we each create the todos in the form of issues on GitHub? I have done some for the cluster-repo component already.

**Comment by jadianes** [comment]
Sure. cluster-web & co have already issues :)
